spring.application.name=envios
server.port=9096
spring.datasource.url= jdbc:mysql://localhost:3307/db_envios
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto= none
spring.jpa.show-sql=true
spring.flyway.enabled= true
spring.flyway.locations= classpath:db/migration
logging.file.name=logs/envios.log

springdoc.enable-hateoas=false

springdoc.swagger-ui.path=/swagger-ui.html

jwt.secret=una_clave_secreta_larga_y_segura_de_al_menos_32_bytes
eureka.instance.prefer-ip-address=true
