spring.application.name=ms-users
server.port=9092
spring.datasource.url=jdbc:mysql://localhost:3307/db_usuario
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
jwt.secret=una_clave_secreta_larga_y_segura_de_al_menos_32_bytes
logging.file.name=logs/ms-users.log
springdoc.enable-hateoas=false

springdoc.swagger-ui.path=/swagger-ui.html

eureka.instance.prefer-ip-address=true
