INSERT INTO producto(nombre, descripcion, precio) VALUES ('AMD Ryzen 5 5600', '6 núcleos, 12 hilos, 3.5GHz a 4.4GHz', 135000);
INSERT INTO producto(nombre, descripcion, precio) VALUES ('Intel Core i7-12700K', '12 núcleos, hasta 5.0GHz, LGA1700', 280000);
INSERT INTO producto(nombre, descripcion, precio) VALUES ('AMD Ryzen 7 7800X3D', 'Líder en gaming, 8 núcleos con 3D V-Cache', 390000);
INSERT INTO producto(nombre, descripcion, precio) VALUES ('NVIDIA RTX 4060 Ti', '8GB GDDR6, Arquitectura Ada Lovelace', 420000);
INSERT INTO producto(nombre, descripcion, precio) VALUES ('AMD Radeon RX 7800 XT', '16GB GDDR6, Ideal para 1440p', 550000);
INSERT INTO producto(nombre, descripcion, precio) VALUES ('NVIDIA RTX 4080 Super', '16GB GDDR6X, Rendimiento entusiasta 4K', 1150000);
INSERT INTO producto(nombre, descripcion, precio) VALUES ('RAM DDR4 16GB 3200MHz', 'Corsair Vengeance LPX CL16 (2x8GB)', 450000);
INSERT INTO producto(nombre, descripcion, precio) VALUES ('RAM DDR5 32GB 6000MHz', 'G.Skill Trident Z5 Neo RGB, optimizado AMD Expo', 115000);
INSERT INTO producto(nombre, descripcion, precio) VALUES ('SSD NVMe 1TB Gen4', 'Kingston NV2, Lectura hasta 3500MB/s', 65000);
INSERT INTO producto(nombre, descripcion, precio) VALUES ('SSD NVMe 2TB Samsung 990 Pro', 'Gen4 de alto rendimiento, 7450MB/s', 175000);
INSERT INTO producto(nombre, descripcion, precio) VALUES ('HDD 2TB Western Digital Blue', '7200 RPM, SATA 6Gb/s para almacenamiento masivo', 55000);
INSERT INTO producto(nombre, descripcion, precio) VALUES ('Placa Madre B550M', 'Micro-ATX para procesadores Ryzen AM4', 95000);
INSERT INTO producto(nombre, descripcion, precio) VALUES ('Placa Madre Z790 WiFi', 'ATX para Intel 12va/13va/14va gen', 240000);
INSERT INTO producto(nombre, descripcion, precio) VALUES ('Fuente 650W 80+ Bronze', 'Corsair CX650M Semi-modular', 75000);
INSERT INTO producto(nombre, descripcion, precio) VALUES ('Fuente 850W 80+ Gold', 'EVGA SuperNOVA, Totalmente modular', 130000);
INSERT INTO producto(nombre, descripcion, precio) VALUES ('Water Cooling 240mm', 'Deepcool LS520 ARGB, doble ventilador', 85000);
INSERT INTO producto(nombre, descripcion, precio) VALUES ('Gabinete Mid-Tower RGB', 'Lateral de vidrio templado, incluye 3 ventiladores', 60000);
INSERT INTO producto(nombre, descripcion, precio) VALUES ('Monitor 27" 144Hz', 'Panel IPS, 1ms de respuesta, Full HD', 185000);
INSERT INTO producto(nombre, descripcion, precio) VALUES ('Mouse Logitech G502 Hero', 'Sensor 25K DPI, pesas ajustables', 45000);
INSERT INTO producto(nombre, descripcion, precio) VALUES ('Teclado Redragon Kumara', 'Mecánico Switch Blue, Retroiluminado', 35000);