CREATE DATABASE IF NOT EXISTS db_productos
CHARACTER SET utf8m4 COLLATE utf8mb4_unicode_ci;

CREATE DATABASE IF NOT EXISTS db_inventario
CHARACTER SET utf8m4 COLLATE utf8mb4_unicode_ci;

CREATE DATABASE IF NOT EXISTS db_usuario
    CHARACTER SET utf8m4 COLLATE utf8mb4_unicode_ci;

CREATE DATABASE IF NOT EXISTS db_carrito
    CHARACTER SET utf8m4 COLLATE utf8mb4_unicode_ci;

CREATE DATABASE IF NOT EXISTS db_ventas
    CHARACTER SET utf8m4 COLLATE utf8mb4_unicode_ci;

CREATE DATABASE IF NOT EXISTS db_recibo
    CHARACTER SET utf8m4 COLLATE utf8mb4_unicode_ci;

CREATE DATABASE IF NOT EXISTS db_reportes
    CHARACTER SET utf8m4 COLLATE utf8mb4_unicode_ci;

CREATE DATABASE IF NOT EXISTS db_envios
    CHARACTER SET utf8m4 COLLATE utf8mb4_unicode_ci;

CREATE DATABASE IF NOT EXISTS db_pagos
    CHARACTER SET utf8m4 COLLATE utf8mb4_unicode_ci;

CREATE DATABASE IF NOT EXISTS db_comentarios
    CHARACTER SET utf8m4 COLLATE utf8mb4_unicode_ci;
